/**
 * PM2 config for DuckClaw Telegram bot (generated by wizard).
 * Start: pm2 start ecosystem.core.config.cjs
 * Token: guardado en .env (auto-cargado por el bot al iniciar).
 */
module.exports = {
  apps: [
    {
      name: "DuckClaw-Brain",
      script: "/Users/juanjosearevalocamargo/Desktop/duckclaw/.venv/bin/python3",
      args: "-m core.integrations.telegram_bot",
      cwd: "/Users/juanjosearevalocamargo/Desktop/duckclaw",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      env: {
        PYTHONPATH: "/Users/juanjosearevalocamargo/Desktop/duckclaw",
        DUCKCLAW_DB_PATH: "/Users/juanjosearevalocamargo/desktop/finanz/finanz.duckdb",
        DUCKCLAW_BOT_MODE: "langgraph",
        DUCKCLAW_LLM_PROVIDER: "mlx",
        DUCKCLAW_LLM_MODEL: "Slayer-8B-v1.1",
        DUCKCLAW_LLM_BASE_URL: "http://127.0.0.1:8080/v1",
      },
    },
  ],
};
